In [53]:
import numpy as np
import sympy as sp

In [54]:
n_u_v= np.array([[1, 0, 0, 0],[0, -1, 0, 0],[0, 0, -1, 0], [0, 0, 0, -1]])
matriz_identidad=np.array([[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, 0], [0, 0, 0, 1]])
n_u_v_2=2*n_u_v
n_u_v_2_I=np.dot(matriz_identidad, n_u_v_2)
print(n_u_v_2_I)


[[ 2  0  0  0]
 [ 0 -2  0  0]
 [ 0  0 -2  0]
 [ 0  0  0 -2]]


In [55]:
r0 = sp.Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
r1 = sp.Matrix([[0, 0, 0, 1], [0, 0, 1, 0], [0, -1, 0, 0], [-1, 0, 0, 0]])
r2= sp.Matrix([[0, 0, 0, -sp.I], [0, 0, sp.I, 0], [0, sp.I, 0, 0], [-sp.I, 0, 0, 0]])
r3 = sp.Matrix([[0, 0, 1, 0], [0, 0, 0, -1], [-1, 0, 0, 0], [0, 1, 0, 0]])

In [56]:
# Calcular {γμ, γν}
gamma_mu = [r0, r1, r2, r3]
anti_commutation = []
for mu in range(4):
    for nu in range(4):
        result = gamma_mu[mu] * gamma_mu[nu] + gamma_mu[nu] * gamma_mu[mu]
        anti_commutation.append(result)

métrica = sp.diag(1, -1, -1, -1)

for mu in range(4):
    for nu in range(4):
        expected_result = 2 * métrica[mu, nu] * sp.eye(4)
      
        if anti_commutation[mu * 4 + nu] == expected_result:
            print("Verificado")
        else:
            print("No verificado")


Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado
Verificado


De esta manera es posible concluir que el álgebra de Clifford está dada por una relación de anticonmutación, antes descrita.