In [5]:
import numpy as np

In [6]:
n_u_v= np.array([[1, 0, 0, 0],[0, -1, 0, 0],[0, 0, -1, 0], [0, 0, 0, -1]])
matriz_identidad=np.array([[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, 0], [0, 0, 0, 1]])
n_u_v_2=2*n_u_v
n_u_v_2_I=np.dot(matriz_identidad, n_u_v_2)
print(n_u_v_2_I)


[[ 2  0  0  0]
 [ 0 -2  0  0]
 [ 0  0 -2  0]
 [ 0  0  0 -2]]


In [7]:
r_0=np.array([[1.0, 0.0, 0.0, 0.0],[0.0, 1.0, 0.0, 0.0],[0.0, 0.0, -1.0, 0.0], [0.0, 0.0, 0.0, -1.0]])
r_1=np.array([[0.0, 0.0, 0.0, 1.0],[0.0, 0.0, 1.0, 0.0],[0.0, -1.0, 0.0, 0.0], [-1.0, 0.0, 0.0, 0.0]])
r_2=np.array([[0.0, 0.0, 0.0, -1j],[0.0, 0.0, 1j, 0.0],[0.0, 1j, 0.0, 0.0], [0.0, 0.0, 0.0, -1j]])
r_3=np.array([[0.0, 0.0, 1.0, 0.0],[0.0, 0.0,0.0, -1.0],[-1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0]])

In [8]:
matrices=[r_0, r_1, r_2, r_3]

for i in range(0, 4):
    for j in range(0, 4):
        x=np.dot(matrices[i], matrices[j]) + np.dot(matrices[j], matrices[i])
        print(x)


[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+2.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[-2.  0.  0.  0.]
 [ 0. -2.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0. -2.]]
[[0.+1.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+1.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+2.j]]
[[0.+1.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+1.j]]
[[ 0.+0.j  0.+0.j  0.+0.j -2.+0.j]
 [ 0.+0.j -2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j  0.+0.j]
 [ 0.+0.j  0.