In [2]:
import numpy as np

A = np.array([[1, 0, 0],[5, 1, 0],[-2, 3, 1]])

B = np.array([[4, -2, 1],[0, 3, 7],[0, 0, 2]])

def multiplicacion(A,B):
      
    M,N = A.shape
    R,T = B.shape
    

    if R==1:
        B=B.reshape(T, R)
        R,T = B.shape
   

    C = np.zeros(shape=(M, T))
    
    if N==R:

        for i in range(M):
            for j in range(T):
                for k in range(0,N):
                    C[i,j] += A[i,k]*(B[k,j])
        
        return C
    
print("mediante nuestro algoritmo de multiplicación de matrices obtenermos el siguiente resultado\n")
print(multiplicacion(A,B))

mediante nuestro algoritmo de multiplicación de matrices obtenermos el siguiente resultado

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
