In [1]:
import numpy as np

In [2]:
b = np.array([-3,-3,8,9])
u_1 = np.array([3,1,0,1])
u_2 = np.array([1,2,1,1])
u_3 = np.array([-1,0,2,-1])
a = np.array([u_1,u_2,u_3])
A = a.T
A

array([[ 3,  1, -1],
       [ 1,  2,  0],
       [ 0,  1,  2],
       [ 1,  1, -1]])

a) Mínimos Cuadrados

In [3]:
ATxA = np.dot(A.T,A)
IATxA=np.linalg.inv(ATxA)

In [4]:
xPARTE1=np.dot(IATxA,A.T)

In [5]:
x=np.dot(xPARTE1,b.T)

In [6]:
Proy=np.dot(A,x)
Proy

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00, -1.33226763e-15])

b) Grand-Schmidt

In [7]:
def normalizar (u_1):
    n_1=u_1/(np.sqrt(np.dot(u_1,u_1)))
    return n_1

In [8]:
def Grand_Schmidt (u_1,u_2,u_3):
    n_1 = normalizar(u_1)
    v_1 = n_1
    v_2 = u_2 - ((np.dot(u_2,v_1))/(np.dot(v_1,v_1)))*v_1
    v_3 = u_3 - ((np.dot(u_3,v_1))/(np.dot(v_1,v_1)))*v_1 - ((np.dot(u_3,v_2))/(np.dot(v_2,v_2)))*v_2

    vn_2,vn_3 = normalizar(v_2),normalizar(v_3)

    Base_orton_st = np.array([v_1,vn_2,vn_3])

    return Base_orton_st

Base_ortonormal = Grand_Schmidt(u_1,u_2,u_3)
Base_ortonormal 

array([[ 0.90453403,  0.30151134,  0.        ,  0.30151134],
       [-0.32961713,  0.75341057,  0.51796977,  0.2354408 ],
       [ 0.25633581, -0.26982716,  0.78249877, -0.49918025]])

In [9]:
def Proyeccion_GM (b,base_orton):
    proyw_b = np.dot(b,base_orton[0])*base_orton[0] + np.dot(b,base_orton[1])*base_orton[1] + np.dot(b,base_orton[2])*base_orton[2]
    return proyw_b

proyeccionb = Proyeccion_GM(b,Base_ortonormal)
proyeccionb

array([-2.00000000e+00,  3.00000000e+00,  4.00000000e+00, -2.22044605e-16])